### ISSUE TITLE
Support disabling default uploader via command line

### ISSUE THREAD

**Issue by hootener** [codecov/codecov-exe#103]
:wave: CTO of Codecov here, and I'm opening this issue due to a request from a few of our enterprise customers using codecov-exe for uploading.

Occasionally, we encounter customers who for various reasons cannot leverage presigned PUT based uploading of coverage reports. In this case, if they're using the bash uploader, we provide two options:

1. use the `-X s3` command line argument when uploading
2. use the `client_uploads: true` flag in their installation yaml

1 and 2 effectively do the same thing, at upload time the presigned PUT based uploader is skipped and the fallback is used directly. My request is as follows: is it possible for codecov-exe to add similar support in its upload behavior? Simply honoring `-X s3` as a command line option that defaults to the CodecovFallbackUploader would do the trick.

Codecov would submit this patch itself, but it currently has no tooling for Windows, nor a deep in house experience with C# or codecov-exe, so we may end up doing more harm than good :). Is there any way we could see this feature implemented?

**Comment by AdmiringWorm** [comment]
I apologize for not having answered earlier (I thought I had).

I have looked a little into what would be necessary to implement this suggestion. Unfortunately, at the moment, it isn't possible to be implemented without some refactoring of the code (unsure at this moment how big of a refactor).

Basically

1. The configuration from the command line is never passed far enough into the code to make a decision on which uploader to use or not use (this is probably the easiest to implement).
2. Currently, there is no handling at all about YAML configurations in the program, so some kind of implementation of handling reading a YAML file will need to be worked on before we can support the `client_uploads: true` flag.

While I hope the necessary changes are less than I expect, unfortunately, I do not have the time at the moment to look into the implementation of such features.

**Comment by hootener** [comment]
Got it. I think suggestion 1, just allowing `-X s3` would be sufficient. If you, or anyone in the community, decides to take this on, please let me know if Codecov can help.

**Comment by AdmiringWorm** [comment]
Disabling the `s3` uploader will be available in the upcoming version of codecov-exe.
The same arguments can be used to disable s3 in this program as in the bash uploader `-X s3` (alternatively `--feature s3` can also be used).
