### ISSUE TITLE
Program returns error code 1 when -required argument is used and no failure occurred

### ISSUE THREAD

**Issue by AdmiringWorm** [codecov/codecov-exe#17]
When calling codecov-exe and the `-required` argument have been used, the program returns an error code of 1 even if the upload actually succeeded.

This looks like it occurs because of the following line in the `Run.cs` file:
https://github.com/codecov/codecov-exe/blob/31f9a9bcc81367a0be19a13f05c7ce401b15b367/Source/Codecov/Program/Run.cs#L20

I'm willing to open a PR if interested

/cc @stevepeak @larzw

**Comment by larzw** [comment]
@AdmiringWorm,
Thanks for reporting this! A pr is very welcome.

**Comment by AdmiringWorm** [comment]
I'll open a PR shortly, it's just a 1 line change though if I'm correct in my assumption.

**Comment by larzw** [comment]
Great..I'll push out a new version to nuget when your done and I'm back to my computer.

**Comment by AdmiringWorm** [comment]
@larzw just opened the PR (will automatically close this one on merge).

BTW, I may have some suggestions sometime in the future for improvements on the chocolatey package.

**Comment by larzw** [comment]
Just merged...I would love feedback on my chocolatey package! This is my first choco package I've created.

**Comment by AdmiringWorm** [comment]
@larzw mind letting me know when it's available on nuget?
Just waiting on it before I can finalize the PR to Cake.Recipe.

**Comment by larzw** [comment]
Yup! I'll ping you in gitter when it's ready..maybe in an hour or so..

**Comment by AdmiringWorm** [comment]
@larzw just had a quick look at the chocolatey nuspec and powershell files, and the first things that popped out was that the software should be embedded (in this case, the powershell could be removed, but a VERIFICATION.txt and LICENSE.txt file would need to be added, the former because the mods and users need a way to verify it comes from an official distribution point).
Another point is that it's missing the `bugTrackerUrl` (or I didn't see it anyhow).

But in all, it's quite good TBH.
