### ISSUE TITLE
Version 1.0.2 is freezing on appveyor

### ISSUE THREAD

**Issue by larzw** [codecov/codecov-exe#26]
@Baune8D reported this issue... Is your repository public so I can see the build? Personally, I"m using version 1.0.2 and did not have any issues...[see](https://ci.appveyor.com/project/larzw/cake-paket/branch/master). Do you have spaces in your project root path by any chance? Any other information so I can re-create the issue would be great. 

Thanks!

**Comment by Baune8D** [comment]
I am afraid not. Its a private work repo.

I run it through Cake with the following packages.config
\<package id="Cake" version="0.21.1" />
\<package id="xunit.runner.console" version="2.2.0" />
\<package id="OpenCover" version="4.6.519" />
\<package id="Codecov" version="1.0.2" />

The code in build.cake:
if (AppVeyor.IsRunningOnAppVeyor)
{
    Codecov("coverage.xml", EnvironmentVariable("CODECOV_TOKEN"));
}

coverage.xml is 4960 KB in size and is generated by OpenCover also through Cake.

Appveyor output was like this for an hour until it timed out:
              _____          _
             / ____|        | |
            | |     ___   __| | ___  ___ _____   __
            | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
            | |___| (_) | (_| |  __/ (_| (_) \ V /
             \_____\___/ \____|\___|\___\___/ \_/
                                         exe-1.0.2
            
2017-08-10 05:06:14 [Information] AppVeyor detected.
2017-08-10 05:06:15 [Information] Git detected.
2017-08-10 05:06:15 [Information] Project root: C:\projects\saxis-platform

That is what i can think of right now. I can try to reproduce it later in a test repo.

**Comment by larzw** [comment]
Thanks @Baune8D! If you could reproduce it in a test repository that would be great!

**Comment by Methuselah96** [comment]
I am also getting the same problem. I will try to replicate when I have time.

**Comment by Methuselah96** [comment]
AppVeyor build: https://ci.appveyor.com/project/Paragon/unitclasslibrary/build/1.0.101
GitHub repo: https://github.com/ParagonTruss/UnitClassLibrary/tree/code-coverage-tests

**Comment by larzw** [comment]
@Methuselah96 
Thanks for recreating this issue! I'll take a peek and try and get a fix out.

**Comment by larzw** [comment]
@Baune8D and @Methuselah96 this is fixed now in version 1.0.3. Let me know if you have anymore issues!

Thanks!
