### ISSUE TITLE
Any known issues with codecov.exe with new GitHub security requirements?

### ISSUE THREAD

**Issue by gep13** [codecov/codecov-exe#35]
I am in the process of updating GitReleaseManager to support the new GitHub Security requirements, and I noticed in the build output that I am getting this:

https://ci.appveyor.com/project/GitTools/gitreleasemanager/build/0.3.0-PullRequest.106+95.build.188#L781

I thought that it was related to the token I was using, but I have updated that, and I am not seeing any difference.

Could it be that the requests that codecov.exe is making are subject to the same security requirements that GtiReleaseManager is now subject to?

Thanks in advance!  @larzw

**Comment by larzw** [comment]
Thanks for the comment @gep13.

/cc @stevepeak would someone on your team have time too look into this for me? I'm super busy right now.

**Comment by AdmiringWorm** [comment]
@gep13 from looking at the build output, it seems like a token isn't actually used.

Can you please verify that the codecov token have been set in the environment variable `CODECOV_TOKEN`?

**Comment by gep13** [comment]
@AdmiringWorm I have set an environment variable called CODECOV_REPO_TOKEN, (which was the one used by Cake.Recipe) however, in this case, it doesn't matter.  AppVeyor doesn't populate environment variables when it is building a PR, so that environment variable is not used.  It seems as though, for some reason, it gets tripped up when finding the project on CodeCov, even though I know it is there.

Any ideas?

**Comment by AdmiringWorm** [comment]
Honestly I don't know right now, from the looks of it the url used is correct when on a non-public repository when a token isn't used.

@stevepeak perhaps there are something on the server preventing the uploading (like the security requirements as @gep13 initially mentioned).

**Comment by AdmiringWorm** [comment]
I believe the cause of the error have been found, it seems that codecov.io doesn't accept encoded pluss signs in the job parameter. I've fixed this locally for now, and is preparing to get a new release out as we speak.

Closing this one though, in favor of #36.

**Comment by gep13** [comment]
@AdmiringWorm that is great work! Thanks for the update!
