### ISSUE TITLE
Support uploading to v2 endpoint

### ISSUE THREAD

**Issue by stevepeak** [codecov/codecov-exe#38]
For enterprise customers there are cases when v4 endpoint is not available. Please add the v2 endpoint as a backup for 405 errors to v4.

Directions are here: https://github.com/codecov/codecov-bash/blob/master/codecov#L1524-L1538

Thanks!

**Comment by AdmiringWorm** [comment]
Just trying to figure out what really is needed to change from the v4 url.

- Changing to v2 url (of course)
- Changing the 'Content-Type' to 'text/plain'
- Adding 'X-Content-Encoding: gzip'
- Adding 'Accept: text/plain'
- Changing from 'PUT' method to 'POST' method.
- Should only upload with v2 if v4 fails with HTTP Status 405

Is the above correct, or have I missed something?

**Comment by stevepeak** [comment]
Hey @AdmiringWorm 👋 I do believe you have it correct 👍

**Comment by snaggled** [comment]
+1

**Comment by AdmiringWorm** [comment]
This have now finally been implemented in the codebase, and will be part of the next release (1.6.0).

It will try the v2 url when the v4 url fails, no matter the response code returned when trying to use the v4 url. (A major restructuring would be needed to be able to implement the fallback only if server returns status code 405).
