### ISSUE TITLE
Add a dotnet tool for codecov exe

### ISSUE THREAD

**Issue by StefH** [codecov/codecov-exe#44]
Can you make a **dotnet global tool** from codecov ?

So that it can be easily used in e.g. Azure Pipelines?
Like
``` cmd
dotnet tool install --global dotnet-codecov
```
or
``` cmd
dotnet tool install --global codecov
```

See also this list from all supported tools until now:
https://github.com/natemcmaster/dotnet-tools

**Comment by AdmiringWorm** [comment]
I'm not familiar with writing dotnet tools.
But I'm guessing it would require quite the rewrite of the application to work as expected, which unfortunately I doubt I would have the time for anytime soon.
Nor am I familiar with azure pipelines for that matter.

I'm not against the idea though.

**Comment by StefH** [comment]
I think it's very easy to convert codecov into a dotnet tool, only things needed are small updates in the `.csproj` file.

Example:
``` xml
<PackAsTool>true</PackAsTool>
```
And then upload as NuGet. (Maybe you need another name because codecov is already there)

See this page: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create
Azure Pipelines was just an example.

**Comment by AdmiringWorm** [comment]
That may be the only change if we were to only provide the dotnet tool, but doing that would also break pretty much every project using codecov-exe already.

I have a few ideas to test out, but unfortunately isn't really in a position to do that right now.

**Comment by StefH** [comment]
An easy work-around is to wrap that extra setting in an IF condition which checks for an environment variable.

Example where this xml is only used when the **buildType** environment variable is set to "DOTNET_TOOL".

``` xml
<PropertyGroup Condition=" '$(buildType)' == 'DOTNET_TOOL' ">
  <PackAsTool>true</PackAsTool>
</PropertyGroup>
```

**Comment by AdmiringWorm** [comment]
@StefH this is one of the paths I was considering to test out.

**Comment by AdmiringWorm** [comment]
The [Codecov.Tool](https://www.nuget.org/packages/Codecov.Tool/) package was just pushed to nuget, it is still indexing so give it some time until it can be used.

Thank you @ViktorHofer for providing the project file to make this available.

**Comment by ViktorHofer** [comment]
Thanks for providing the tool! 👍
