### ISSUE TITLE
Add support for Azure Pipelines

### ISSUE THREAD

**Issue by clairernovotny** [codecov/codecov-exe#50]
The tool does not currently automatically detect the build server variables from Azure Pipelines.

The variables are all documented here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by jerrode** [comment]
Thanks for bringing this up, @onovotny -- we are seeing more and more usage of Azure Pipelines.

@hootener was doing some work on his previously. Eli, any thoughts here?

**Comment by hootener** [comment]
@onovotny submitted PR #51 . Awaiting review from @AdmiringWorm.

Thanks for the submission!

**Comment by AdmiringWorm** [comment]
A new version with the support for Azure Pipelines was just pushed to nuget ~(and chocolatey)~.

Give it some time until it have been indexed.

EDIT: Now the chocolatey package was pushed as well 😄
