### ISSUE TITLE
azure pipeline is broken

### ISSUE THREAD

**Issue by glennawatson** [codecov/codecov-exe#55]
In the change introduced by @onovotny, for the POST url you are sending 

&service=azurepipelines

This value is not supported by the codecov api and causes a 400 status code error.

As mentioned in https://docs.codecov.io/reference#upload it's not part of the listed supported pipelines. 

```
[
  "travis",
  "buildbot",
  "circleci",
  "buddybuild",
  "solano",
  "teamcity",
  "appveyor",
  "wercker",
  "magnum",
  "shippable",
  "codeship",
  "drone.io",
  "jenkins",
  "semaphore",
  "gitlab",
  "bamboo",
  "snap",
  "buildkite",
  "bitrise",
  "greenhouse",
  "custom"
]
```

We should probably change to `custom` until there is support for the azure pipelines?

**Comment by ghost** [comment]
Do you know if there is a way to workaround this issue for now until the fix is merged?

**Comment by AdmiringWorm** [comment]
@dgriffen unfortunately, there in no way to work around it.
I do plan to review the opened PR's this weekend, and get out a new release with when those are merged.
