### ISSUE TITLE
Support glob expression for file paths

### ISSUE THREAD

**Issue by hanabi1224** [codecov/codecov-exe#68]
It will be very helpful to add glob pattern support to -f parameter

**Comment by AdmiringWorm** [comment]
not a bad idea, and definitely something I would like to have.
I have added some comments on your PR on some things that need to be changed.

**Comment by hanabi1224** [comment]
@AdmiringWorm I have resolved your comments and updated my PR, please let me know if there're still any outstanding issues, thx!
