### ISSUE TITLE
--file cannot handle paths with spaces

### ISSUE THREAD

**Issue by jnm2** [codecov/codecov-exe#71]
Using 1.5.0

```ps1
$testResultsDir = 'artifacts\Test results'

codecov --name $tfm --file "$testResultsDir\coverage.$tfm.xml" --token $env:CODECOV_TOKEN
```

```
WRN The file D:\a\1\s\artifacts\Test does not exist.
WRN The file results\coverage.net472.xml does not exist.
FTL No Report detected.
```

It should respect quotes by using the string[] args that dotnet passes to Program.Main.

With this hypothetical call:

```ps1
codecov --file "artifacts\Test results\a.xml" "artifacts\Test results\b.xml"
```

Program.Main will receive this as args:
```cs
new[]
{
    "--file",
    "artifacts\Test results\a.xml",
    "artifacts\Test results\b.xml"
}
```

Given such arguments, the files collection should contain `artifacts\Test results\a.xml` and `artifacts\Test results\b.xml`, not `artifacts\Test`, `results\a.xml`, `artifacts\Test`, `results\b.xml`.

**Comment by jnm2** [comment]
Workaround:

```ps1
# Workaround for https://github.com/codecov/codecov-exe/issues/71
$codecovFullPath = Join-Path (Get-Location) $codecov
Push-Location $testResultsDir

& $codecovFullPath --name $tfm --file coverage.$tfm.xml --token $env:CODECOV_TOKEN

# Workaround for https://github.com/codecov/codecov-exe/issues/71
Pop-Location
```

**Comment by AdmiringWorm** [comment]
Unfortunately this is a limitation of the command parsing library being used, and how it has been set up.
CommandLineParser
While I am not 100% sure, I do believe the following needs to be used to get around it:

```powershell
$testResultsDir = 'artifacts\Test results'

codecov --name $tfm --file "'$testResultsDir\coverage.$tfm.xml'" --token $env:CODECOV_TOKEN
```
(Notice the single quotes used after and before the double quote).

> `codecov --file "artifacts\Test results\a.xml" "artifacts\Test results\b.xml"`

Passing multiple file paths this way is not supported unfortunately, all paths are expected to be within a singe quote string, using either single or double quotes.

IE:
```powershell
codecov --file '"artifacts\Test results\a.xml" "artifacts\Test results\b.xml"'
```
Or
```powershell
codecov --file "'artifacts\Test results\a.xml' 'artifacts\Test results\b.xml'"
```
(Again, I am not 100% certain it works with spaces).

If the mentioned ways do not work, then I am afraid that this won't be fixed until v 2.0 of codecov-exe (where I plan a major overhaul of the program, and changing how the arguments get parsed, changing the argument parser, changing the arguments to be similar but not exactly the same as the codecov bash script).

**Comment by jnm2** [comment]
Thanks.

`--file "'$testResultsDir\coverage.$tfm.xml'"` has the same result as without the single quotes.

**Comment by AdmiringWorm** [comment]
I was almost afraid of that.
Most likely in is the result of the separator used on the argument attribute (https://github.com/codecov/codecov-exe/blob/master/Source/Codecov/Program/CommandLineOptions.cs#L74).

I will investigate and see if this is something we are able to handle with the current library used, and without a breaking change.

**Comment by AdmiringWorm** [comment]
Unfortunately I have not been able to figure out how to fix this in a non-breaking way, as such I am afraid that this will not be fixed until the next major version have been released (which I have not yet started working on).

I will add a new section to the readme for Known Issues with a reference to this issue.

**Comment by jnm2** [comment]
Thanks for looking and for the tool! I appreciate both.

**Comment by AdmiringWorm** [comment]
Not a problem.

You should actually thank @larzw for the tool. While I am the one maintaining the tool now, he was the one that created it and most of the codebase is his work.

**Comment by jnm2** [comment]
Thanks @larzw! 😊

Semi-related, have you seen https://github.com/dotnet/command-line-api/wiki/DragonFruit-overview?

**Comment by AdmiringWorm** [comment]
No I had not, but I will make a note of it before deciding which parser to change to.

I was actually thinking of changing to [Spectre.Cli](https://github.com/spectresystems/spectre.cli), which have most of the features I want (and some others in the planning stage).

**Comment by AdmiringWorm** [comment]
I have been looking into this issue a little more, and it actually turns out that it isn't a limitation with the commandline parser, but rather something we had done wrong while using it instead.

I have a fix ready, but not sure if I will be pushing it today or not (as I have already pushed 2 versions today, and want to wait a little in case those introduced other issues).

**Comment by PureKrome** [comment]
Woot cheers!
