### ISSUE TITLE
Prevent download progress output?

### ISSUE THREAD

**Issue by FantasticFiasco** [codecov/codecov-exe#75]
Is it possible to prevent displaying the download progress? A majority of my build log looks like this.

```
Progress: Downloading codecov 1.5.0... 73%
Progress: Downloading codecov 1.5.0... 73%
...
```

**Comment by AdmiringWorm** [comment]
You will need to look up the documentation of the package manager you are using to download codecov-exe. (chocolatey, nuget, dotnet cli).

We don't output any downloading in the program itself.

If you are using chocolatey, you can use the `--no-progress` argument. I do not know with the others.
