### ISSUE TITLE
Azure pipelines no longer needs a token

### ISSUE THREAD

**Issue by sharwell** [codecov/codecov-exe#93]
The **master** branch documentation says that the Azure Pipelines uploads require the Codecov token be specified. Starting with #92, this is no longer the case.

📝 I was not able to update the documentation with #92, because the changes were made in **master** and not present in **develop**.

**Comment by AdmiringWorm** [comment]
It can still be updated in the develop branch (and honestly should).

This branch gets merged into master when a new release is being prepared (I noticed some unit tests was failing on github action, so need to look into that before preparing a new release though).
