### ISSUE TITLE
Support .NET Core 3.x for Codecov.Tool

### ISSUE THREAD

**Issue by lkurzyniec** [codecov/codecov-exe#95]
I've just moved my app to `.NET Core 3.1` (which is LTS). I switched my CI from `dotnet 2.2` to `dotnet 3.1` and received such error:
```
$ $HOME/.dotnet/tools/codecov -f ./test/CoverageResults/coverage.opencover.xml -t $CODECOV_TOKEN
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.16.04-x64
The command "$HOME/.dotnet/tools/codecov -f ./test/CoverageResults/coverage.opencover.xml -t $CODECOV_TOKEN" exited with 150.
```

Full details here: https://travis-ci.com/lkurzyniec/netcore-boilerplate/jobs/268203227

**Comment by AdmiringWorm** [comment]
Thank you for opening this issue.

I have added support for 3.x in the repository source, however I do not expect to make a new release anytime soon.
In the meantime you can grab the latest pre-release with this change from the appveyor server with the following command:
```
dotnet tool install -g Codecov.Tool --add-source "https://ci.appveyor.com/nuget/codecov-exe" --version "1.10.0-unstable0001"
```

**Comment by lkurzyniec** [comment]
Got it. Thx!

**Comment by jetersen** [comment]
@AdmiringWorm you say you don't plan to release anytime soon?
Any timeframe?

The changes so far seems very minor: https://github.com/codecov/codecov-exe/compare/develop to add support for dotnet 3.x

**Comment by AdmiringWorm** [comment]
@casz no, I do not have any timeframe.
The only thing I can say for sure is that it won't be until at least after new year.

**Comment by AdmiringWorm** [comment]
This have now been assigned to the next release, which I hope to be able to create some time later this week.

**Comment by AdmiringWorm** [comment]
@lkurzyniec @casz version 1.10.0 was just released now, and support for .NET Core 3.x have been added to the Codecov.Tool package.

**Comment by jetersen** [comment]
Many thanks 🙇
